**AUTHOR : SUBHAM TEWARI**
    
ALL COPYRIGHTS RESERVED

### Importing Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

So we have imported these three most used libraries in Machine Learning

### Importing Dataset 

In [31]:
dataset=pd.read_csv('/home/illegal/Desktop/Machine_Learning_A2Z_Udemy/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Data.csv')

Using Pandas we have imported the dataset 

In [32]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### Feature Selection

In [33]:
X = dataset.iloc[:, :-1].values

In [34]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [55]:
y = dataset.iloc[:, 3].values

In [56]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

Y is the dependent variable vector

Now as we can see that there are many missing data in the dataset so we have to do something to make it feasible.
So one way is to remove the rows which has missing data or else we can use imputer in **sckit-learn** library to fill in those missing values with the most appropriate values

In [57]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN',strategy='mean',axis=0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])

So in this you can see that we have found out the missing data and then using Imputer we have filled those missing values with the mean of that row

In [58]:
X

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.40000000e+01,   7.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   2.70000000e+01,   4.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   3.00000000e+01,   5.40000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   3.80000000e+01,   6.10000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   4.00000000e+01,   6.37777778e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   3.50000000e+01,   5.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   3.87777778e+01,   5.20000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.80000000e+01,   7.90000000e+04],


So now there are no missing values

### Dealing with Categorical Data

Now as there are two columns which contain categorical data we have to encode them with numbers so that we can apply machine learning models on them

In [59]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder #Label Encoder is used to encode categorical data

In [60]:
labelencoder_X=LabelEncoder()
X[:, 0]=labelencoder_X.fit_transform(X[:, 0])
X

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.40000000e+01,   7.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   2.70000000e+01,   4.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   3.00000000e+01,   5.40000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   3.80000000e+01,   6.10000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   4.00000000e+01,   6.37777778e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   3.50000000e+01,   5.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   3.87777778e+01,   5.20000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.80000000e+01,   7.90000000e+04],


So you can see that the categorical values have been converted to numeric values

Now one problem that can arise is that the machine learning model can think that as France is 0 and Spain is 2,so it means Spain has bigger or has more priority but that is not the case,so we have to do something so that the model does not misinterprets the data.

We will use OneHotEncoder to deal with this problem

In [61]:
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()
X

array([[  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   4.40000000e+01,
          7.20000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   2.70000000e+01,
          4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   3.00000000e+01,
          5.40000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   3.80000000e+01,
          6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   4.00000000e+01,
          6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   3.50000000e+01,
          5.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00

Now we can see that there are three columns one for Spain, France and Italy respectively.So if France is the option then the three rows will have values 1,0,0

In [62]:
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Splitting the dataset into training and testing data

In [63]:
from sklearn.cross_validation import train_test_split

/home/illegal/.local/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [64]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

So here we have choosen test size to be 20% of the full data set and the random_state can be anything you like but if you want to have the same result like me use 0

### Feature Scaling

Lets say that the features age and salary are on a different scale and ML algorithms are mostly based on euclidean distances and so the euclidean distance between two salaries will be much larger than that of the age.So basically we have to do somthing to bring them to the same scale and there comes Feature Scaling.We have to normalize the feature values in order to increase the accuracy of your model.So we will use Standard Scalar library in sklearn and using it we will be scaling the X_train and X_test.

In [70]:
from sklearn.preprocessing import StandardScaler

In [72]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)