#### AUTHOR: SUBHAM TEWARI

#### ALL COPYRIGHTS RESERVED

# Numpy Basics

### How to create a Rank 1 Numpy Array

In [2]:
import numpy as np

an_array=np.array([3,33,333]) # Create a Rank 1 array

print(type(an_array)) # Type of an nd array is <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


### Now we will check the dimensions of nd array that we created and it will be of a single dimension

In [11]:
print(an_array.shape) #Dimension of the nd array

(3,)


### Now we will print each element in the nd array using array indices

In [4]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


### Now we will modify the value of the array index 0

In [5]:
an_array[0]=888 # Nd array are mutable

print(an_array)

[888  33 333]


### How to create an Rank 2 array using numpy

Rank two **ndarray** is one with two dimensions.Notice the format below [[row1],[row2]]

In [12]:
another=np.array([[2,22,222],[4,44,444]]) # Rank 2 array

print(another) # print the elements in the nd array

print("The shape is 2 rows and 3 columns: ",another.shape) # shape of the np array

print("Accessing the elements with indices [0,0],[0,1],[1,0] in the np array: ",another[0,0],another[0,1],another[1,0]) # Printing elements with indices [0,0],[0,1],[1,0] of the np aray

[[  2  22 222]
 [  4  44 444]]
The shape is 2 rows and 3 columns:  (2, 3)
Accessing the elements with indices [0,0],[0,1],[1,0] in the np array:  2 22 4


### There are many ways to create a numpy array

Here we create many **numpy array** with different sizes with different shapes and pre filled values

In [30]:
import numpy as np

ex1=np.zeros((2,2)) # Create a 2*2 array filled with zeros

print(ex1) # print the nd array

[[ 0.  0.]
 [ 0.  0.]]


In [32]:
ex2=np.full((2,2),9.0) # Create a 2*2 array filled with 9.0

print(ex2)  # print the nd array

[[ 9.  9.]
 [ 9.  9.]]


In [37]:
ex3=np.eye(2,2) # Create a 2*2 array with diagonals elements 1

print(ex3) # print the nd array

[[ 1.  0.]
 [ 0.  1.]]


In [40]:
ex4=np.ones((1,2)) # Create an array with all values 1s

print(ex4) # print the nd array

[[ 1.  1.]]


In [41]:
ex5=np.random.random((2,2)) # Create a 2*2 matrix using random numbers
 
print(ex5) # print the nd array

[[ 0.78963215  0.19506274]
 [ 0.72316859  0.04177671]]


### Array Indexing

In [55]:
import numpy as np

an_array=np.array([[1,11,111,1111],[2,22,222,2222],[3,33,333,3333],[4,44,444,4444]]) # Create a nd array with shape(3,4)

print(an_array) #print the nd array

[[   1   11  111 1111]
 [   2   22  222 2222]
 [   3   33  333 3333]
 [   4   44  444 4444]]


Use **array slicing** to create a subarray with first two rows and two columns

In [85]:
a_slice=an_array[:2,1:3] # Create a sub array with first two rows and two columns

print(a_slice) # print the nd array

[[  11  111]
 [3022  222]]


Now if we modify **a_slice** array it will reflect in the original an_array because a_slice is just a reference of the original array **an_array** 

In [86]:
print("Before assigning: ",an_array[0,1]) 

a_slice[0,0]=0

print("Value after assigning: ",an_array[0,1])

Before assigning:  11
Value after assigning:  0


So we can see that even when we change the value of a_slice array of index (0,0) it is being reflected in the original array named an_array

Now to create a sub array which doesn't modify the original array we have to do it in **another way**

In [87]:
import numpy as np

an_array=np.array([[1,11,111,1111],[2,22,222,2222],[3,33,333,3333],[4,44,444,4444]]) # Create a nd array with shape(3,4)

print(an_array) #print the nd array

[[   1   11  111 1111]
 [   2   22  222 2222]
 [   3   33  333 3333]
 [   4   44  444 4444]]


In [88]:
a_slice=np.array(an_array[:2,1:3])

print(a_slice)

[[ 11 111]
 [ 22 222]]


In [89]:
print("Before assigning: ",an_array[0,1])

a_slice[0,0]=0

print("After assigning: ",an_array[0,1])

Before assigning:  11
After assigning:  11


So we can see that the original array **an_array** even though we changed the value of the **a_slice** array

### Indexing and Slicing 

In [90]:
import numpy as np

an_array=np.array([[1,11,111,1111],[2,22,222,2222],[3,33,333,3333],[4,44,444,4444]])

print(an_array)

[[   1   11  111 1111]
 [   2   22  222 2222]
 [   3   33  333 3333]
 [   4   44  444 4444]]


In [91]:
row_rank1=an_array[1,:] # Using indexing and slicing produces an array of lower rank

print(row_rank1,row_rank1.shape) # Notice only one []

[   2   22  222 2222] (4,)


In [92]:
row_rank2=an_array[1:2,:] # Using slicing generates an array of same rank

print(row_rank2,row_rank2.shape) # Notice only one [[]]

[[   2   22  222 2222]] (1, 4)


We will do the same thing with the columns now

In [93]:
col_rank1=an_array[:,1] # Rank 1

print(col_rank1,col_rank1.shape)

print()

col_rank2=an_array[:,1:2] # Rank 2

print(col_rank2,col_rank2.shape)

[11 22 33 44] (4,)

[[11]
 [22]
 [33]
 [44]] (4, 1)


### Array Indexing for changing elements

In [94]:
import numpy as np

an_array=np.array([[1,11,111,1111],[2,22,222,2222],[3,33,333,3333],[4,44,444,4444]])

print(an_array)

[[   1   11  111 1111]
 [   2   22  222 2222]
 [   3   33  333 3333]
 [   4   44  444 4444]]


Now we will create an array with indices

In [95]:
col_indices=np.array([0,1,2,0])

print("\nCol Indices picked: ",col_indices)

row_indices=np.arange(4)

print("\nRow indices picked: ",row_indices)


Col Indices picked:  [0 1 2 0]

Row indices picked:  [0 1 2 3]


In [96]:
for row,col in zip(row_indices,col_indices):
    
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [97]:
print("Values of array at those indices: ",an_array[row_indices,col_indices])

Values of array at those indices:  [  1  22 333   4]


In [98]:
an_array[row_indices,col_indices]+=1000

print("\nChanged Array:")

print("\n",an_array)


Changed Array:

 [[1001   11  111 1111]
 [   2 1022  222 2222]
 [   3   33 1333 3333]
 [1004   44  444 4444]]


### Boolean Indexing 

In [100]:
# create a 3*2 array

an_array=np.array([[11,12],[21,22],[31,32]])

print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [102]:
# create a filter which will give true if the condition is met and false if the condition is not matched

filter=an_array>15

filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

**Notice:** The filter array is of the same size as the nd array an_array which is filled with True if the corresponding element is >15 and false if the corresponding element is <15

In [103]:
# Now we can select only those elements which meet the criteria

print(an_array[filter])

[21 22 31 32]


In [105]:
# For short we can do it in one line

an_array[an_array>15]

array([21, 22, 31, 32])

This is very useful as we can also change the actual value of the elements in the array applying some logical filter

In [106]:
an_array[an_array%2==0]+=100

print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


### Datatypes and Array Operations

**<span style="color:red">Datatypes:</span>**

In [109]:
ex1=np.array([11,12]) #Python assigns the datatype

print(ex1.dtype)

int64


In [111]:
ex1=np.array([11.0,12.0]) #Python assigns the datatype

print(ex1.dtype)

float64


In [114]:
ex3=np.array([11.0,12.0],dtype=np.int64) #User can also assign the datatype 

print(ex3.dtype)

int64


In [121]:
ex4=np.array([11.8,12.4],dtype=np.int64) #User can also assign the datatype and use it force the floats into integers(floor function)

print(ex4.dtype)

print()

print(ex4)

int64

[11 12]


In [122]:
ex5=np.array([11,12],dtype=np.float64) #User can also assign the datatype and convert the integers into float as we don't lose any data

print(ex5.dtype)

print()

print(ex5)

float64

[ 11.  12.]


### Arithmetic Array Operations:

In [124]:
x=np.array([[11,22],[21,31]],dtype=np.int) 

y=np.array([[12.2,13.4],[14.6,16.7]],dtype=np.float64)

print(x)

print()

print(y)

[[11 22]
 [21 31]]

[[ 12.2  13.4]
 [ 14.6  16.7]]


Now we will add both the arrays

In [126]:
print(x+y) #Plus sign works

print()

print(np.add(x,y)) # More suitable with np.add()

[[ 23.2  35.4]
 [ 35.6  47.7]]

[[ 23.2  35.4]
 [ 35.6  47.7]]


In [128]:
print(x-y) #Minus sign works

print()

print(np.subtract(x,y)) # More suitable with np.subtract()

[[ -1.2   8.6]
 [  6.4  14.3]]

[[ -1.2   8.6]
 [  6.4  14.3]]


In [129]:
print(x*y) #Multiply sign works

print()

print(np.multiply(x,y)) # More suitable with np.multiply()

[[ 134.2  294.8]
 [ 306.6  517.7]]

[[ 134.2  294.8]
 [ 306.6  517.7]]


In [130]:
print(x/y) #Divide sign works

print()

print(np.divide(x,y)) # More suitable with np.multiply()

[[ 0.90163934  1.64179104]
 [ 1.43835616  1.85628743]]

[[ 0.90163934  1.64179104]
 [ 1.43835616  1.85628743]]


In [133]:
#Square root of all the elements of an array

print(np.sqrt(x))

[[ 3.31662479  4.69041576]
 [ 4.58257569  5.56776436]]


In [134]:
#Exponent of all the elements in the array

print(np.exp(x))

[[  5.98741417e+04   3.58491285e+09]
 [  1.31881573e+09   2.90488497e+13]]


### Statistical Methods,Sorting and Set Operations

**<span style="color:blue",font size:32>Basic Statistical Operations:</span>**

In [137]:
# Setup an 2*5 array with random elements

arr=10*np.random.randn(2,5)

print(arr)

[[  5.56586055   1.80138458  17.12806386 -17.10988161   6.45168485]
 [  8.4512      12.97101804  14.40123016 -20.4668741   -2.49270923]]


In [138]:
# Printing the mean of all the elements of the array

print(arr.mean())

2.67009771032


In [141]:
# We can also get the mean of all the elements of each row of an array

print(arr.mean(axis=1))

[ 2.76742245  2.57277298]


In [142]:
# We can also compute the mean of all the elements of each column of an array

print(arr.mean(axis=0))

[  7.00853027   7.38620131  15.76464701 -18.78837785   1.97948781]


In [143]:
# We can also compute the sum of all the elements of an array

print(arr.sum())

26.7009771032


In [146]:
# We can also compute the medians of all the elements of each row in the array

print(np.median(arr,axis=1))

[ 5.56586055  8.4512    ]


**<span style="color:blue",font size:32>Sorting:</span>**

In [149]:
# Create a array of random elements

unsorted=np.random.randn(10)

print(unsorted)

[ 0.20191329 -1.69535181 -0.24742385 -0.73901397  0.13781639 -1.95696971
 -1.86013086 -0.51548782 -0.90163687  0.6263631 ]


In [155]:
# Create a copy and then sort the array

sorted=np.array(unsorted)

sorted.sort()

print("\nSorted Array:\n",sorted)

print("\nUnsorted Array:\n",unsorted)


Sorted Array:
 [-1.95696971 -1.86013086 -1.69535181 -0.90163687 -0.73901397 -0.51548782
 -0.24742385  0.13781639  0.20191329  0.6263631 ]

Unsorted Array:
 [ 0.20191329 -1.69535181 -0.24742385 -0.73901397  0.13781639 -1.95696971
 -1.86013086 -0.51548782 -0.90163687  0.6263631 ]


**<span style="color:blue",font size:32>Finding Unique Elements:</span>**

In [158]:
array=np.array([1,2,1,3,4,5,4,1,4,7,8,5]) # Array contains duplicate values

print(np.unique(array)) # Print only unique values

[1 2 3 4 5 7 8]


**<span style="color:blue",font size:32>Set Operations with np.array data types:</span>**

In [159]:
# Create two arrays 

s1=np.array(["bulb","chair","desk"])

s2=np.array(["lamp","bulb","chair"])

print(s1,s2)

['bulb' 'chair' 'desk'] ['lamp' 'bulb' 'chair']


In [163]:
print(np.intersect1d(s1,s2)) # Gives the intersection of the two arrays

['bulb' 'chair']


In [164]:
print(np.union1d(s1,s2)) # Gives the union of the two arrays

['bulb' 'chair' 'desk' 'lamp']


In [168]:
print(np.setdiff1d(s1,s2)) # Gives the elements in S1 that are not in S2

['desk']


In [167]:
print(np.in1d(s1,s2)) # Gives the elements in S1 which are also in S2 in boolean values

[ True  True False]


### Broadcasting

In [170]:
# Create a 4*3 array of zeros

array=np.zeros((4,3))

print(array)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [171]:
# Create a rank 1 nd array with three values 

add_rows=np.array([1,0,2])

print(add_rows)

[1 0 2]


In [172]:
y=array+add_rows # add each row of array using add_rows

print(y)

[[ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]]


So here we can see that we want to add a row matrix add_rows to each of the rows of array then we can do it in numpy by using broadcasting

In [177]:
# Create a nd array of 4*1 to broadcast along columns

add_columns=np.array([[0,1,2,3]])

add_columns=add_columns.T

print(add_columns)

[[0]
 [1]
 [2]
 [3]]


In [179]:
y=array+add_columns #add to each column of the array

print(y)

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]


In [181]:
# This will broadcast in both the dimensions

add_scalar=np.array([1])

print(array+add_scalar)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
